version: 2.1
machine:
  environment:
    # Set Environment Variable in circleci app
    GCLOUD_PROJECT: ${GCLOUD_PROJECT}

dependencies:
  pre:
    - curl -o $HOME/google_appengine_1.9.40.zip https://storage.googleapis.com/appengine-sdks/features/google_appengine_1.9.40.zip 
    - unzip -q -d $HOME $HOME/google_appengine_1.9.40.zip
    # Retrieve our secrets from the CircleCI environment
    - echo $CLIENT_SECRET | base64 --decode > ${HOME}/client-secret.json 
    
    - pip install --upgrade pip setuptools webapp2 jinja webob
      # Update gcloud
    - gcloud --quiet components update app
      # authenticate gcloud
    - gcloud auth activate-service-account --key-file ${HOME}/client-secret.son 
      # Replace <your-project-id>
    - gcloud config set project ${GCLOUD_PROJECT} 

jobs:
  run_tests:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            pip install --user -r requirements.txt
      - run:
          name: Run Unit Tests
          command: |
            pytest --junitxml=test-reports/junit.xml
      - store_test_results:
          path: test-reports

workflows:
  build_test:
    jobs:
      - run_tests

deployment:
  staging:
    branch: master
    command:
      - gcloud -q app deploy app.yaml --promote --version=1
